print('Create on tabada')
x = int(input('Type a value any: '))
igual = str('=')
a = (x * 1)
b = (x * 2)
c = (x * 3)
d = (x * 4)
e = (x * 5)
print('-'*12)
print(f' {x} x 1 = {a}\n {x} x 2 = {b}\n {x} x 3 = {c}\n {x} x 4 = {d}\n {x} x 5 = {e}...')
print('-'*12)