print('Dissecando uma variável')
value = input('Type a value any: ')
print('O tipo primitivo dessa variável é', type(value))
print('-'*20)
print('É número/letra?', value.isalnum())
print('É um valor numérico?', value.isnumeric())
print('É uma string? ', value.isalpha())
print('É um valor decimal?', value.isdecimal())
print('É identação?', value.isidentifier())
print('É um digito? ',value.isdigit())
print('E um dígito binário (ascii)?', value.isascii())