import time
print('Cálculo de desconto no produto')
value = float(input('Digite o valor que deseja tirar a prcentagem: R$'))
time.sleep(0.5)
procv = int(input('Digite a porcentagem: '))
time.sleep(1)
print('...')
time.sleep(1)
print('...'), time.sleep(1)
print('O barato é louco e o processo é lento...')
time.sleep(1.8)
print('-'*30)
form = (value * procv / 100)
new = (value - form)
print(f'O valor de R${value} com o desconto de {procv}% ...')
print(f'Terá abatido o valor de R${form:.2f}, que por sua vez\n pasará a sobrar R${new:.2f} ')